"""
VIRASAT — Menu Blueprint Routes
Provides the interactive menu page and a JSON API endpoint for client-side filtering.
"""
from flask import render_template, request, jsonify
from . import menu

# ── Complete curated menu catalogue ──────────────────────────────────────────
MENU_ITEMS = [
    # ── Starters ──────────────────────────────────────────────────────────────
    {
        "id": 1,
        "name": "Subz Gilafi Seekh",
        "category": "starters",
        "category_label": "Starters",
        "description": "Minced vegetables and aromatic herbs encased in a vivid coat of julienned bell peppers, slow-kissed in our clay tandoor over live coals.",
        "price": 260,
        "is_veg": True,
        "tags": ["Chef's Pick", "Tandoor"],
        "image": "dish1_v4.png",
        "spice": "medium",
    },
    {
        "id": 2,
        "name": "Malai Soya Chaap",
        "category": "starters",
        "category_label": "Starters",
        "description": "Tender soya chaap marinated overnight in a velvety cloak of hung curd, fresh cream, and mace — roasted to a golden blush.",
        "price": 290,
        "is_veg": True,
        "tags": ["Bestseller"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 3,
        "name": "Paneer Tikka Royale",
        "category": "starters",
        "category_label": "Starters",
        "description": "Thick-cut cottage cheese marinated in saffron-tinged royal masala, char-grilled and served with mint chutney and kachumber salad.",
        "price": 260,
        "is_veg": True,
        "tags": ["Vegetarian"],
        "image": "dish1_v4.png",
        "spice": "medium",
    },
    {
        "id": 4,
        "name": "Nadru Ke Kebab",
        "category": "starters",
        "category_label": "Starters",
        "description": "A Kashmiri heirloom recipe — gossamer minced lotus stem with thirty-seven secret spices, melt-in-the-mouth on iron skewers.",
        "price": 320,
        "is_veg": True,
        "tags": ["Heritage Recipe", "Chef's Pick"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 5,
        "name": "Dahi ke Sholay",
        "category": "starters",
        "category_label": "Starters",
        "description": "Bread triangles filled with spiced yogurt, green chillies, and fresh herbs, golden-fried to a satisfying crunch.",
        "price": 220,
        "is_veg": True,
        "tags": ["Vegetarian", "Crispy"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 6,
        "name": "Tandoori Broccoli",
        "category": "starters",
        "category_label": "Starters",
        "description": "Fresh broccoli florets blended with cashew paste, Parmesan, and saffron water — incredibly delicate in texture and flavour.",
        "price": 290,
        "is_veg": True,
        "tags": ["Silky Soft"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    # ── Royal Main Course ──────────────────────────────────────────────────────
    {
        "id": 7,
        "name": "Kashmiri Dum Aloo",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "A Kashmiri crown jewel — slow-braised baby potatoes in a majestic broth of Kashmiri chillies, whole spices, and caramelised onions.",
        "price": 330,
        "is_veg": True,
        "tags": ["Heritage Recipe", "Kashmiri"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 8,
        "name": "Paneer Makhani",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "The legendary paneer makhani — tandoor-roasted cottage cheese simmered in a rich tomato-fenugreek velvet sauce with Amul butter and fresh cream.",
        "price": 370,
        "is_veg": True,
        "tags": ["Bestseller", "Mild & Rich"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 9,
        "name": "Dal Makhani",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Black lentils and kidney beans slow-cooked for eighteen hours over a wood fire, finished with a generous tempering of butter and cream.",
        "price": 330,
        "is_veg": True,
        "tags": ["Vegetarian", "Slow-Cooked"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 10,
        "name": "Navratan Korma",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Royal Mughal court recipe — nine jewels of vegetables and nuts in a luscious cardamom-and-almond gravy, perfumed with rose water.",
        "price": 400,
        "is_veg": True,
        "tags": ["Mughal Heritage", "Chef's Pick"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 11,
        "name": "Paneer Lababdar",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Chunky cottage cheese wedges in a robustly spiced roasted tomato and cashew gravy with a flutter of kasoori methi.",
        "price": 360,
        "is_veg": True,
        "tags": ["Vegetarian"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 12,
        "name": "Shahi Kofta",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Saffron-scented paneer and raisin dumplings poached in a velvety golden-hued gravy of cashews and poppy seeds.",
        "price": 390,
        "is_veg": True,
        "tags": ["Vegetarian", "Royal"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    # ── Biryanis ──────────────────────────────────────────────────────────────
    {
        "id": 13,
        "name": "Hyderabadi Kathal Dum Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "Aged Basmati sealed under a golden crust with marinated jackfruit, fried shallots, mint, and saffron milk — a royal feast in a vessel.",
        "price": 430,
        "is_veg": True,
        "tags": ["Signature", "Dum Cooked"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 14,
        "name": "Lucknowi Gucchi Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "The nawabi pukka style — rice and premium morel mushrooms cooked separately, then layered and sealed, producing a silkier, more aromatic result.",
        "price": 540,
        "is_veg": True,
        "tags": ["Heritage Recipe"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 15,
        "name": "Nawabi Paneer Tikka Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "Char-grilled paneer tikka marinated in coconut and star anise, layered with fragrant Basmati and sealed with dough — a royal offering.",
        "price": 450,
        "is_veg": True,
        "tags": ["Vegetarian", "Premium"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 16,
        "name": "Subz Dum Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "A garden of seasonal vegetables, paneer, and lotus seeds slow-cooked with aged Basmati and aromatic whole spices — delicate and fragrant.",
        "price": 400,
        "is_veg": True,
        "tags": ["Vegetarian", "Aromatic"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    # ── Desserts ──────────────────────────────────────────────────────────────
    {
        "id": 17,
        "name": "Shahi Tukda",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Double-fried bread triangles soaked in rose-scented sugar syrup, crowned with reduced saffron rabri and edible silver leaf.",
        "price": 190,
        "is_veg": True,
        "tags": ["Royal", "Chef's Pick"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 18,
        "name": "Rasmalai",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Gossamer cottage cheese discs poached in saffron-and-cardamom milk, garnished with pistachios and rose petals — the queen of Indian sweets.",
        "price": 180,
        "is_veg": True,
        "tags": ["Bestseller", "Classic"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 19,
        "name": "Gulab Jamun",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Soft khoya dumplings fried to a deep amber, immersed in warm rose-and-saffron sugar syrup, served with vanilla kulfi.",
        "price": 150,
        "is_veg": True,
        "tags": ["Classic"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 20,
        "name": "Kesar Phirni",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Creamy ground rice pudding set in terracotta bowls with generous threads of Kashmiri saffron, pistachios, and a whisper of cardamom.",
        "price": 160,
        "is_veg": True,
        "tags": ["Traditional"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 21,
        "name": "Kulfi Falooda",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Dense hand-churned pistachio kulfi atop vermicelli noodles, rose syrup, basil seeds, and chilled milk — a street-royal fusion.",
        "price": 220,
        "is_veg": True,
        "tags": ["Fusion", "Cold"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    # ── Shahi Thalis ──────────────────────────────────────────────────────────
    {
        "id": 22,
        "name": "Maharaja Veg Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "The ultimate royal vegetarian spread: Nadru Kebab, Kashmiri Dum Aloo, Paneer Makhani, Dal Makhani, Shahi Kofta, Laccha Paratha, Saffron Rice, Raita, Pickle & Gulab Jamun.",
        "price": 1150,
        "is_veg": True,
        "tags": ["Feast", "Includes Dessert", "Premium"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 23,
        "name": "Maharani Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "A vegetarian royal repast: Paneer Tikka, Shahi Kofta, Dal Makhani, Paneer Lababdar, Subz Biryani, Phulka, Raita, Pickle & Rasmalai.",
        "price": 1000,
        "is_veg": True,
        "tags": ["Vegetarian", "Feast", "Includes Dessert"],
        "image": "dish3_v4.png",
        "spice": "medium",
    },
    {
        "id": 24,
        "name": "Nawabi Veg Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "Lucknawi-style grandeur: Tandoori Broccoli, Navratan Korma, Subz Dum Biryani, Warqi Paratha, Shorba, Raita & Kesar Phirni — a Nawab's complete banquet.",
        "price": 1080,
        "is_veg": True,
        "tags": ["Nawabi Heritage", "Feast", "Includes Dessert"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    # ── Beverages ─────────────────────────────────────────────────────────────
    {
        "id": 25,
        "name": "Masala Chaas",
        "category": "beverages",
        "category_label": "Beverages",
        "description": "Traditional buttermilk spiced with roasted cumin, mint, and green chilli — a perfect palate cleanser.",
        "price": 80,
        "is_veg": True,
        "tags": ["Cold", "Classic"],
        "image": "bev_generic.png",
        "spice": "mild",
    },
    {
        "id": 26,
        "name": "Kesar Badam Milk",
        "category": "beverages",
        "category_label": "Beverages",
        "description": "Warm milk simmered with saffron, crushed almonds, and cardamom.",
        "price": 120,
        "is_veg": True,
        "tags": ["Warm", "Comfort"],
        "image": "bev_generic.png",
        "spice": "none",
    },
    {
        "id": 27,
        "name": "Mango Lassi",
        "category": "beverages",
        "category_label": "Beverages",
        "description": "Thick, sweet yogurt blended with Alphonso mangoes and a touch of cardamom.",
        "price": 110,
        "is_veg": True,
        "tags": ["Cold", "Bestseller"],
        "image": "bev_generic.png",
        "spice": "none",
    },
]

# Valid category keys
VALID_CATEGORIES = {"starters", "mains", "biryanis", "desserts", "thalis", "beverages"}


@menu.route("/menu")
def index():
    """Render the interactive menu page."""
    return render_template("menu.html", menu_items=MENU_ITEMS)


@menu.route("/api/menu")
def api_menu():
    """
    JSON API — Returns menu items, optionally filtered by category.
    Query params:
        category (str): one of starters | mains | biryanis | desserts | thalis | all
    """
    category = request.args.get("category", "all").lower().strip()
    if category == "all" or category not in VALID_CATEGORIES:
        items = MENU_ITEMS
    else:
        items = [item for item in MENU_ITEMS if item["category"] == category]
    return jsonify(items)
