"""
VIRASAT — Menu Blueprint Routes
Provides the interactive menu page and a JSON API endpoint for client-side filtering.
"""
from flask import render_template, request, jsonify
from . import menu

# ── Complete curated menu catalogue ──────────────────────────────────────────
MENU_ITEMS = [
    # ── Starters ──────────────────────────────────────────────────────────────
    {
        "id": 1,
        "name": "Gilafi Seekh Kebab",
        "category": "starters",
        "category_label": "Starters",
        "description": "Minced lamb and aromatic herbs encased in a vivid coat of julienned bell peppers, slow-kissed in our clay tandoor over live coals.",
        "price": 420,
        "is_veg": False,
        "tags": ["Chef's Pick", "Tandoor"],
        "image": "dish1_v4.png",
        "spice": "medium",
    },
    {
        "id": 2,
        "name": "Murgh Malai Tikka",
        "category": "starters",
        "category_label": "Starters",
        "description": "Tender chicken supremes marinated overnight in a velvety cloak of hung curd, fresh cream, and mace — roasted to a golden blush.",
        "price": 480,
        "is_veg": False,
        "tags": ["Bestseller"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 3,
        "name": "Paneer Tikka Royale",
        "category": "starters",
        "category_label": "Starters",
        "description": "Thick-cut cottage cheese marinated in saffron-tinged royal masala, char-grilled and served with mint chutney and kachumber salad.",
        "price": 380,
        "is_veg": True,
        "tags": ["Vegetarian"],
        "image": "dish1_v4.png",
        "spice": "medium",
    },
    {
        "id": 4,
        "name": "Kakori Kebab",
        "category": "starters",
        "category_label": "Starters",
        "description": "A Lucknawi heirloom recipe — gossamer minced lamb with raw papaya and thirty-seven secret spices, melt-in-the-mouth on iron skewers.",
        "price": 520,
        "is_veg": False,
        "tags": ["Heritage Recipe", "Chef's Pick"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 5,
        "name": "Dahi ke Sholay",
        "category": "starters",
        "category_label": "Starters",
        "description": "Bread triangles filled with spiced yogurt, green chillies, and fresh herbs, golden-fried to a satisfying crunch.",
        "price": 320,
        "is_veg": True,
        "tags": ["Vegetarian", "Crispy"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    {
        "id": 6,
        "name": "Reshmi Murgh Kebab",
        "category": "starters",
        "category_label": "Starters",
        "description": "Silky chicken mince blended with cashew paste, Parmesan, and saffron water — incredibly delicate in texture and flavour.",
        "price": 460,
        "is_veg": False,
        "tags": ["Silky Soft"],
        "image": "dish1_v4.png",
        "spice": "mild",
    },
    # ── Royal Main Course ──────────────────────────────────────────────────────
    {
        "id": 7,
        "name": "Rogan Josh",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "A Kashmiri crown jewel — slow-braised lamb shanks in a majestic broth of Kashmiri chillies, whole spices, and caramelised onions.",
        "price": 680,
        "is_veg": False,
        "tags": ["Heritage Recipe", "Kashmiri"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 8,
        "name": "Murgh Makhani",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "The legendary butter chicken — tandoor-roasted poultry simmered in a rich tomato-fenugreek velvet sauce with Amul butter and fresh cream.",
        "price": 620,
        "is_veg": False,
        "tags": ["Bestseller", "Mild & Rich"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 9,
        "name": "Dal Makhani",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Black lentils and kidney beans slow-cooked for eighteen hours over a wood fire, finished with a generous tempering of butter and cream.",
        "price": 480,
        "is_veg": True,
        "tags": ["Vegetarian", "Slow-Cooked"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 10,
        "name": "Gosht Shahi Korma",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Royal Mughal court recipe — tender lamb in a luscious cardamom-and-almond gravy, perfumed with rose water and finished with saffron.",
        "price": 760,
        "is_veg": False,
        "tags": ["Mughal Heritage", "Chef's Pick"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    {
        "id": 11,
        "name": "Paneer Lababdar",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Chunky cottage cheese wedges in a robustly spiced roasted tomato and cashew gravy with a flutter of kasoori methi.",
        "price": 520,
        "is_veg": True,
        "tags": ["Vegetarian"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 12,
        "name": "Shahi Kofta",
        "category": "mains",
        "category_label": "Royal Main Course",
        "description": "Saffron-scented paneer and raisin dumplings poached in a velvety golden-hued gravy of cashews and poppy seeds.",
        "price": 560,
        "is_veg": True,
        "tags": ["Vegetarian", "Royal"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    # ── Biryanis ──────────────────────────────────────────────────────────────
    {
        "id": 13,
        "name": "Hyderabadi Dum Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "Aged Basmati sealed under a golden crust with marinated lamb, fried shallots, mint, and saffron milk — a Nizam's feast in a vessel.",
        "price": 750,
        "is_veg": False,
        "tags": ["Signature", "Dum Cooked"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 14,
        "name": "Lucknowi Gosht Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "The nawabi pukka style — rice and succulent mutton cooked separately, then layered and sealed, producing a silkier, more aromatic result.",
        "price": 820,
        "is_veg": False,
        "tags": ["Heritage Recipe"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 15,
        "name": "Nawabi Prawn Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "Coastal tiger prawns marinated in coconut and star anise, layered with fragrant Basmati and sealed with dough — a coastal royal offering.",
        "price": 920,
        "is_veg": False,
        "tags": ["Seafood", "Premium"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 16,
        "name": "Subz Dum Biryani",
        "category": "biryanis",
        "category_label": "Biryanis",
        "description": "A garden of seasonal vegetables, paneer, and lotus seeds slow-cooked with aged Basmati and aromatic whole spices — delicate and fragrant.",
        "price": 580,
        "is_veg": True,
        "tags": ["Vegetarian", "Aromatic"],
        "image": "dish2_v4.png",
        "spice": "mild",
    },
    # ── Desserts ──────────────────────────────────────────────────────────────
    {
        "id": 17,
        "name": "Shahi Tukda",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Double-fried bread triangles soaked in rose-scented sugar syrup, crowned with reduced saffron rabri and edible silver leaf.",
        "price": 280,
        "is_veg": True,
        "tags": ["Royal", "Chef's Pick"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 18,
        "name": "Rasmalai",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Gossamer cottage cheese discs poached in saffron-and-cardamom milk, garnished with pistachios and rose petals — the queen of Indian sweets.",
        "price": 260,
        "is_veg": True,
        "tags": ["Bestseller", "Classic"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 19,
        "name": "Gulab Jamun",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Soft khoya dumplings fried to a deep amber, immersed in warm rose-and-saffron sugar syrup, served with vanilla kulfi.",
        "price": 220,
        "is_veg": True,
        "tags": ["Classic"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 20,
        "name": "Kesar Phirni",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Creamy ground rice pudding set in terracotta bowls with generous threads of Kashmiri saffron, pistachios, and a whisper of cardamom.",
        "price": 240,
        "is_veg": True,
        "tags": ["Traditional"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    {
        "id": 21,
        "name": "Kulfi Falooda",
        "category": "desserts",
        "category_label": "Desserts",
        "description": "Dense hand-churned pistachio kulfi atop vermicelli noodles, rose syrup, basil seeds, and chilled milk — a street-royal fusion.",
        "price": 320,
        "is_veg": True,
        "tags": ["Fusion", "Cold"],
        "image": "dish3_v4.png",
        "spice": "none",
    },
    # ── Shahi Thalis ──────────────────────────────────────────────────────────
    {
        "id": 22,
        "name": "Maharaja Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "The ultimate royal spread: Kakori Kebab, Rogan Josh, Murgh Makhani, Dal Makhani, Shahi Kofta, Laccha Paratha, Saffron Rice, Raita, Pickle & Gulab Jamun.",
        "price": 1850,
        "is_veg": False,
        "tags": ["Feast", "Includes Dessert", "Premium"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
    {
        "id": 23,
        "name": "Maharani Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "A vegetarian royal repast: Paneer Tikka, Shahi Kofta, Dal Makhani, Paneer Lababdar, Subz Biryani, Phulka, Raita, Pickle & Rasmalai.",
        "price": 1450,
        "is_veg": True,
        "tags": ["Vegetarian", "Feast", "Includes Dessert"],
        "image": "dish3_v4.png",
        "spice": "medium",
    },
    {
        "id": 24,
        "name": "Nawabi Thali",
        "category": "thalis",
        "category_label": "Shahi Thalis",
        "description": "Lucknawi-style grandeur: Reshmi Kebab, Gosht Korma, Hyderabadi Biryani, Warqi Paratha, Shorba, Raita & Kesar Phirni — a Nawab's complete banquet.",
        "price": 1650,
        "is_veg": False,
        "tags": ["Nawabi Heritage", "Feast", "Includes Dessert"],
        "image": "dish2_v4.png",
        "spice": "medium",
    },
]

# Valid category keys
VALID_CATEGORIES = {"starters", "mains", "biryanis", "desserts", "thalis"}


@menu.route("/menu")
def index():
    """Render the interactive menu page."""
    return render_template("menu.html", menu_items=MENU_ITEMS)


@menu.route("/api/menu")
def api_menu():
    """
    JSON API — Returns menu items, optionally filtered by category.
    Query params:
        category (str): one of starters | mains | biryanis | desserts | thalis | all
    """
    category = request.args.get("category", "all").lower().strip()
    if category == "all" or category not in VALID_CATEGORIES:
        items = MENU_ITEMS
    else:
        items = [item for item in MENU_ITEMS if item["category"] == category]
    return jsonify(items)
